# filename: hunter.py

import asyncio
import logging
from contextlib import contextmanager
from typing import Generator, Dict, Any
import json

from sqlalchemy.orm import Session
import pandas as pd

# مقامی امپورٹس
import database_crud as crud
from utils import fetch_twelve_data_ohlc, convert_candles_to_dataframe
from messenger import send_telegram_alert
from models import SessionLocal
from websocket_manager import manager
from roster_manager import get_hunting_roster
from config import api_settings

# --- نئے، اپ گریڈ شدہ امپورٹس ---
import regime_analyzer
from strategy_scalper import (
    run_trend_following_strategy, 
    run_mean_reversion_strategy, 
    run_breakout_strategy
)
# fusion_engine کی جگہ اب ہم براہ راست reasonbot استعمال کریں گے
from reasonbot import generate_reason 

logger = logging.getLogger(__name__)

# --- کنفیگریشن سے مستقل اقدار ---
PERSONALITIES_FILE = "asset_personalities.json"

@contextmanager
def get_db_session() -> Generator[Session, None, None]:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

def load_asset_personalities() -> Dict:
    try:
        with open(PERSONALITIES_FILE, 'r') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        logger.error(f"{PERSONALITIES_FILE} نہیں ملی یا خراب ہے۔ ڈیفالٹ شخصیت استعمال کی جائے گی۔")
        return {}

async def hunt_for_signals_job():
    """
    یہ جاب وقفے وقفے سے چلتی ہے، تجزیے کے لیے جوڑوں کا انتخاب کرتی ہے،
    اور ہر جوڑے کے لیے مقداری تجزیہ چلاتی ہے۔
    """
    logger.info("🏹 شکاری انجن (ایپیکس ورژن): نئے مواقع کی تلاش کا نیا دور شروع...")
    
    try:
        with get_db_session() as db:
            pairs_to_analyze = get_hunting_roster(db)
        
        if not pairs_to_analyze:
            logger.info("🏹 شکاری انجن: تجزیے کے لیے کوئی اہل جوڑا نہیں۔ تلاش کا دور ختم۔")
            return

        personalities = load_asset_personalities()
        
        tasks = [
            analyze_single_pair(pair, personalities) 
            for pair in pairs_to_analyze
        ]
        await asyncio.gather(*tasks)

    except Exception as e:
        logger.error(f"شکاری انجن کے کام میں ایک غیر متوقع خرابی پیش آئی: {e}", exc_info=True)
    
    logger.info("🏹 شکاری انجن (ایپیکس ورژن): تلاش کا دور مکمل ہوا۔")

async def analyze_single_pair(pair: str, personalities: Dict):
    """
    ایک انفرادی جوڑے کا گہرا تجزیہ کرتا ہے، مارکیٹ کی حالت کا تعین کرتا ہے،
    اور پھر اس حالت کے لیے مخصوص حکمت عملی چلاتا ہے۔
    """
    logger.info(f"🔬 [{pair}] کا مقداری تجزیہ شروع کیا جا رہا ہے...")
    
    try:
        with get_db_session() as db:
            if crud.get_active_signal_by_symbol(db, pair):
                logger.info(f"🔬 [{pair}] تجزیہ روکا گیا: اس جوڑے کا سگنل پہلے سے فعال ہے۔")
                return

        # ہمیں GARCH اور Hurst کے لیے زیادہ ڈیٹا چاہیے
        candles = await fetch_twelve_data_ohlc(pair, "15min", 200)
        
        if not candles or len(candles) < 150: # کم از کم 150 کینڈلز کی ضرورت ہے
            logger.warning(f"📊 [{pair}] تجزیہ روکا گیا: ناکافی کینڈل ڈیٹا ({len(candles) if candles else 0})۔")
            return

        df = convert_candles_to_dataframe(candles)
        df['symbol'] = pair
        
        # مرحلہ 1: مارکیٹ کی حالت کی تشخیص کریں
        market_regime = regime_analyzer.get_market_regime(df)
        
        analysis_result = None
        symbol_personality = personalities.get(pair, personalities.get("DEFAULT", {}))

        # مرحلہ 2: حالت کی بنیاد پر صحیح ہتھیار کا انتخاب کریں
        if market_regime == "Calm_Trending":
            analysis_result = run_trend_following_strategy(df, symbol_personality)
        elif market_regime == "Volatile_Trending":
            analysis_result = run_breakout_strategy(df, symbol_personality)
        elif market_regime == "Quiet_Ranging":
            analysis_result = run_mean_reversion_strategy(df, symbol_personality)
        else: # "Violent_Ranging" or "No_Trade_Zone"
            logger.info(f"🛑 [{pair}] ٹریڈنگ معطل۔ وجہ: مارکیٹ کی حالت '{market_regime}' ہے۔")
            return

        # مرحلہ 3: نتیجہ پروسیس کریں
        if analysis_result and analysis_result.get("status") == "ok":
            # یہاں ہم ایک سادہ اعتماد کا اسکور تفویض کر سکتے ہیں یا اسے مستقبل میں بہتر بنا سکتے ہیں
            confidence = 85.0 # ڈیفالٹ اعلیٰ اعتماد
            strategy_type = analysis_result.get("strategy", "نامعلوم")
            
            # ایک بہتر وجہ بنائیں (یہاں news_data اور pattern_data کو نظر انداز کیا گیا ہے)
            reason = f"A {analysis_result['signal'].upper()} signal was generated by the {strategy_type} strategy in a {market_regime} market regime."
            
            final_signal_data = {
                "status": "ok",
                "symbol": pair,
                "signal": analysis_result['signal'],
                "reason": reason,
                "confidence": confidence,
                "timeframe": "15min",
                "price": analysis_result['price'],
                "tp": analysis_result['tp'],
                "sl": analysis_result['sl'],
                "strategy_type": strategy_type,
                "signal_grade": "A-Grade" # فرض کریں کہ تمام سگنل اعلیٰ معیار کے ہیں
            }

            logger.info(f"✅ [{pair}] سگنل منظور! حکمت عملی: {strategy_type}, حالت: {market_regime}")
            
            with get_db_session() as db:
                update_result = crud.add_or_update_active_signal(db, final_signal_data)
            
            if update_result:
                signal_obj = update_result.signal.as_dict()
                asyncio.create_task(send_telegram_alert(signal_obj))
                asyncio.create_task(manager.broadcast({"type": "new_signal", "data": signal_obj}))
        
        else:
            reason = analysis_result.get("reason", "کوئی سگنل نہیں") if analysis_result else "کوئی سگنل نہیں"
            logger.info(f"ℹ️ [{pair}] کوئی سگنل نہیں بنا۔ وجہ: {reason}")

    except Exception as e:
        logger.error(f"🔬 [{pair}] کے تجزیے کے دوران ایک غیر متوقع خرابی پیش آئی: {e}", exc_info=True)
            
