services:
  # سروس 1: ویب سرور جو API اور فرنٹ اینڈ کو سنبھالے گا
  - type: web
    name: scalpmaster-ai-api
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    
  # سروس 2: پس منظر کا ورکر جو صرف ایک بار چلے گا
  - type: worker
    name: scalpmaster-ai-worker
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: "python background_worker.py"

databases:
  - name: scalpmaster-db
    databaseName: scalpmaster_db
    user: scalpmaster_user
    plan: free
