# filename: render.yaml

services:
  - type: web
    name: scalpmaster-ai-api
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    
    # ★★★ یہ سیکشن شامل کریں ★★★
    # یہ یقینی بناتا ہے کہ ضروری سسٹم لائبریریز انسٹال ہوں
    build:
      apt:
        - build-essential
    # ★★★ یہاں تک ★★★

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scalpmaster-db
          property: connectionString
      - key: TWELVE_DATA_API_KEYS
        sync: false
      - key: MARKETAUX_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

databases:
  - name: scalpmaster-db
    databaseName: scalpmaster_db
    user: scalpmaster_user
    plan: free
