services:
  - type: web
    name: scalpmaster-ai-api
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    
    # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
    # ★★★ اہم اور حتمی تبدیلی: Gunicorn کو صرف 1 ورکر کے ساتھ چلانے کی کمانڈ ★★★
    # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
    startCommand: "gunicorn -w 1 -k uvicorn.workers.UvicornWorker -c gunicorn_conf.py app:app"
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scalpmaster-db
          property: connectionString
      - key: TWELVE_DATA_API_KEYS
        sync: false
      - key: MARKETAUX_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

databases:
  - name: scalpmaster-db
    databaseName: scalpmaster_db
    user: scalpmaster_user
    plan: free
