services:
  - type: web
    name: signal-api
    runtime: python
    repo: https://github.com/arhosting4/fastapi-signal-api
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TWELVE_DATA_API_KEY
        sync: false
    autoDeploy: true
    region: oregon
