# render.yaml
services:
  - type: web
    name: signal-api
    # No runtime specified, Render will automatically detect Dockerfile
    repo: https://github.com/arhosting4/fastapi-signal-api
    branch: main
    # No buildCommand or startCommand needed, Dockerfile handles it
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
    autoDeploy: true
    region: oregon
