# filename: render.yaml

services:
  - type: web
    name: scalpmaster-ai-api
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    
    # ★★★ اہم اور حتمی تبدیلی ★★★
    startCommand: "gunicorn -c gunicorn_conf.py -w 4 -k uvicorn.workers.UvicornWorker app:app"
    
    envVars:
      # ... (باقی envVars ویسے ہی رہیں گے) ...
