# filename: render.yaml
services:
  - type: web
    name: scalpmaster-ai-api
    env: python
    region: oregon
    plan: free # یا آپ کی ضرورت کے مطابق
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DATABASE_URL
        fromDatabase:
          name: scalpmaster-db
          property: connectionString
      - key: TWELVE_DATA_API_KEYS
        sync: false # Render ڈیش بورڈ میں سیٹ کریں
      - key: MARKETAUX_API_KEY
        sync: false # Render ڈیش بورڈ میں سیٹ کریں
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Render ڈیش بورڈ میں سیٹ کریں
      - key: TELEGRAM_CHAT_ID
        sync: false # Render ڈیش بورڈ میں سیٹ کریں

databases:
  - name: scalpmaster-db
    databaseName: scalpmaster_db
    user: scalpmaster_user
    plan: free # یا آپ کی ضرورت کے مطابق
