# filename: render.yaml

services:
  # ویب سروس جو FastAPI ایپلیکیشن کو چلائے گی
  - type: web
    name: scalpmaster-ai-api
    # تعیناتی کا علاقہ
    region: oregon 
    # تعیناتی کا ذریعہ: Docker
    env: docker
    # گٹ ہب برانچ جس سے تعینات کرنا ہے
    branch: main
    # صحت کی جانچ کا راستہ تاکہ Render کو معلوم ہو کہ سروس چل رہی ہے
    healthCheckPath: /health
    # Dockerfile کا راستہ
    dockerfilePath: ./Dockerfile
    # سروس کا پلان (ٹیسٹنگ کے لیے مفت)
    plan: free 
    
    # ماحولیاتی متغیرات
    envVars:
      # ڈیٹا بیس کا URL خود بخود ڈیٹا بیس سروس سے حاصل کریں
      - key: DATABASE_URL
        fromDatabase:
          name: scalpmaster-db
          property: connectionString
      # یہ متغیرات Render کے ڈیش بورڈ میں محفوظ طریقے سے سیٹ کیے جائیں گے
      - key: TWELVE_DATA_API_KEYS
        sync: false
      - key: MARKETAUX_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      # لاگنگ کی سطح کو کنٹرول کرنے کے لیے
      - key: LOG_LEVEL
        value: INFO

# ڈیٹا بیس سروس (PostgreSQL)
databases:
  - name: scalpmaster-db
    databaseName: scalpmaster_db
    user: scalpmaster_user
    # ڈیٹا بیس کا پلان (ٹیسٹنگ کے لیے مفت)
    plan: free
    
