# render.yaml
python:
  version: 3.11.6 # Python version you are using
services:
  - type: web
    name: signal-api
    runtime: python
    repo: https://github.com/arhosting4/fastapi-signal-api
    branch: main
    # UPDATED: Simplified buildCommand
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
    autoDeploy: true
    region: oregon
