services:
  - type: web
    name: fastapi-signal-api
    env: docker
    # --- CRITICAL FIX: Increase Memory for Build ---
    # This gives more RAM to the build process, preventing crashes
    # when installing large libraries like pandas and numpy.
    plan: starter # Use starter plan for better performance
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scalp-master-db # یہاں اپنے Render ڈیٹا بیس کا نام لکھیں
          property: connectionString
      - key: TWELVE_DATA_API_KEY_1
        sync: false
      - key: TWELVE_DATA_API_KEY_2
        sync: false
      - key: TWELVE_DATA_API_KEY_3
        sync: false
      - key: MARKETAUX_API_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

databases:
  - name: scalp-master-db
    databaseName: scalp_master_db
    user: scalp_master_user
    plan: free
